name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ronitacr20354.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -t ronitacr20354.azurecr.io/frontend:latest ./frontend
        docker push ronitacr20354.azurecr.io/frontend:latest

    - name: Build and push backend image
      run: |
        docker build -t ronitacr20354.azurecr.io/backend:latest ./backend
        docker push ronitacr20354.azurecr.io/backend:latest

    - name: Deploy using docker-compose
      run: |
        az webapp config container set \
          --name ${{ secrets.APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose-azure.yml \
          --container-registry-url https://${{ secrets.ACR_NAME }}.azurecr.io \
          --container-registry-user ${{ secrets.ACR_USERNAME }} \
          --container-registry-password ${{ secrets.ACR_PASSWORD }}

- name: Restart webapp to pick up new images
  run: az webapp restart \
    --name ${{ secrets.APP_NAME }} \
    --resource-group ${{ secrets.RESOURCE_GROUP }}
