name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ronitacr20354.azurecr.io   # ✅ Replace with your real ACR login server
        username: ${{ secrets.ACR_USERNAME }}    # ✅ Make sure this secret exists
        password: ${{ secrets.ACR_PASSWORD }}    # ✅ Make sure this secret exists

    - name: Build and push frontend image
      run: |
        docker build -t ronitacr20354.azurecr.io/frontend:latest ./frontend
        docker push ronitacr20354.azurecr.io/frontend:latest

    - name: Build and push backend image
      run: |
        docker build -t ronitacr20354.azurecr.io/backend:latest ./backend
        docker push ronitacr20354.azurecr.io/backend:latest

    - name: Deploy using docker-compose
      run: |
        az webapp config container set \
          --name ${{ secrets.APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose-azure.yml \
          --docker-registry-server-url https://ronitacr20354.azurecr.io \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
